### ISSUE TITLE
提现报错invalid amount

### ISSUE THREAD

**Issue by uioprty** [HuobiRDCenter/huobi_Java#38]
Exception in thread "main" com.huobi.client.exception.HuobiApiException: [Executing] invalid-amount: Parameter `amount` is invalid.
	at com.huobi.client.impl.RestApiInvoker.checkResponse(RestApiInvoker.java:35)
	at com.huobi.client.impl.RestApiInvoker.callSync(RestApiInvoker.java:90)
	at com.huobi.client.impl.SyncRequestImpl.withdraw(SyncRequestImpl.java:342)

WithdrawRequest withdrawRequest = new WithdrawRequest("xxx",
				new BigDecimal(0.01), "btc");
		long withdrawId = syncRequestClient.withdraw(withdrawRequest);

用的1.0.8-SNAPSHOT版本，我看账户里显示的最小提币数据应该是0.01，为什么会提币失败？

**Comment by uioprty** [comment]
0.01需要用string类型，否则转成bigdecimal时会出现尾巴
