### ISSUE TITLE
Exception in syncClient.getPriceDepth if parameter size greater than market depth

### ISSUE THREAD

**Issue by amurdev** [HuobiRDCenter/huobi_Java#56]
If parameter **size** for `syncClient.getPriceDepth` call is greater than market depth client throws exception.

Code sample:
```
SyncRequestClient syncClient = SyncRequestClient.create();

PriceDepth priceDepth = syncClient.getPriceDepth("wavesusdt", 150);
```

Stake Trace:
```
com.huobi.client.exception.HuobiApiException: [Json] Index is out of bound or array is null
	at com.huobi.client.impl.utils.JsonWrapperArray.getArrayAt(JsonWrapperArray.java:39)
	at com.huobi.client.impl.RestApiRequestImpl.lambda$getPriceDepth$24(RestApiRequestImpl.java:710)
	at com.huobi.client.impl.RestApiInvoker.callSync(RestApiInvoker.java:131)
	at com.huobi.client.impl.RestApiInvoker.callSync(RestApiInvoker.java:106)
	at com.huobi.client.impl.SyncRequestImpl.getPriceDepth(SyncRequestImpl.java:122)
	at com.tradisys.commons.exchange.huobi.HuobiApiTest.investigateHuobiApi(HuobiApiTest.java:18)```

**Comment by YXQ212526** [comment]
sdk 已更新至v2版本
