### ISSUE TITLE
连不上啊

### ISSUE THREAD

**Issue by dcy652701** [HuobiRDCenter/huobi_Java#65]
java.net.SocketTimeoutException: connect timed out
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:606)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:117)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:283)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:195)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:249)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:108)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:76)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:245)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)
	at com.huobi.utils.ConnectionFactory.execute(ConnectionFactory.java:70)
	at com.huobi.service.huobi.connection.HuobiRestConnection.executeGet(HuobiRestConnection.java:47)
	at com.huobi.service.huobi.HuobiGenericService.getTimestamp(HuobiGenericService.java:84)
	at client.demo.HuobiDemo.main(HuobiDemo.java:9)
	Suppressed: java.net.SocketTimeoutException: connect timed out

**Comment by jiaosw** [comment]
使用V.P.N.可以的

**Comment by penger** [comment]
> 使用V.P.N.可以的

我用了VPN还是连接不上呢

**Comment by XiaodongFu** [comment]
> 使用V.P.N.可以的

时好时坏，老哥有遇到吗？

**Comment by jiaosw** [comment]
秘密:
//private String restHost = "https://api.huobi.pro";
    private String restHost = "https://api.huobi.de.com";

**Comment by CJR10032** [comment]
> 秘密:
> //private String restHost = "https://api.huobi.pro";
> private String restHost = "https://api.huobi.de.com";

api.huobi.de.com 被也被墙了吧，你们还能连上吗？有别的不用挂代理的域名不？

**Comment by penger** [comment]
api.huobi.bo



在 2021-08-13 21:57:32，"CJR10032" ***@***.***> 写道：

秘密:
//private String restHost = "https://api.huobi.pro";
private String restHost = "https://api.huobi.de.com";

api.huobi.de.com 被也被墙了吧，你们还能连上吗？有别的不用挂代理的域名不？

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CJR10032** [comment]
> api.huobi.bo 在 2021-08-13 21:57:32，"CJR10032" ***@***.***> 写道： 秘密: //private String restHost = "https://api.huobi.pro"; private String restHost = "https://api.huobi.de.com"; api.huobi.de.com 被也被墙了吧，你们还能连上吗？有别的不用挂代理的域名不？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

大佬有新的代理域名吗？以前的都用不了了，我之前都是挂梯子跑的程序，结果今天我用的梯子跑路了。。。
